#!/bin/bash

set -euox pipefail

if [[ "${BUILDKITE_COMMAND}" == "buildkite-agent pipeline upload"* ]]; then
  image_repo_name=datadog-custom-checks
  image_registry_repository="${REGISTRY_HOST}/${image_repo_name}"

  export IMAGE_TAG="$(tc-build-number "${image_repo_name}")"
  export DOCKER_TAG="${image_registry_repository}:${IMAGE_TAG}"
  export DOCKER_TAG_BUILDER="${image_registry_repository}:builder-${IMAGE_TAG}"
  export CACHE_ID="$(md5sum < requirements.txt | awk '{print $1}')"
fi
